[BE] 컨트롤러 중복되는 파일 제거
codesquad-memeber-2020/signup-4 pull request #51
Opened 2020-03-27 07:24 UTC by jypthemiracle

2020-04-07 12:21 UTC, kyucumber requested changes

2020-04-07 12:21 UTC, kyucumber commented on BE-workspace/build.gradle
> +	compile group: 'io.springfox', name: 'springfox-swagger-ui', version: '2.7.0'
swagger가 compile로 의존성이 추가되어야 할 이유가 있을까요?

compile로 해도 당장은 빌드 속도에 큰 영향은 없겠지만, 의존성이 늘어나면 영향을 끼칠 수 있습니다.

그리고 compile은 Gradle 버전이 올라가면서 deprecate 된걸로 알고 있어요

- **implementation**

implementation 사용 시 Gradle은 해당 종속성과 그 종속성에 직접 연결된 모듈만 다시 컴파일한다.

- **api**

api를 이용한 의존성 추가 시 해당 의존성에 액세스할 권한이 있는 모듈을 모두 다시 컴파일한다.

- **compileOnly**

컴파일시에만 종속성이 필요한 경우(lombok, queryDSL) 사용한다.

- **runtimeOnly**

Gradle이 런타임 시에 사용하도록 빌드 출력에만 종속성을 추가한다. 즉, 컴파일 클래스 경로에는 추가되지 않는다.

- **annotationProcessor**

annotationProcessing이 필요한 의존성의 경우(lombok, queryDSL) 이 옵션을 지정해야 한다.

annotationProcessor가 필요없는 작업의 경우에 이 작업이 분리되어 빌드 속도가 향상될 수 있다.


제가 대충 정리해둔거라 잘못된 내용이 있을 수 있어요

gradle 의존성 추가 옵션 관련해선 아래 문서에 잘 정리되어 있습니다.

안드로이드 문서니까 의존성 추가 부분만 보시면 될 것 같아요

https://developer.android.com/studio/build/dependencies

당장 크게 중요한 내용은 아니니 그냥 넘어가셔도 무방합니다.

2020-04-07 12:21 UTC, kyucumber commented on BE-workspace/src/main/java/com/codesquad/signup4/controller/auth/UserLoginController.java
> +}
코드와는 별개의 내용이긴 한데..

위에 파일에도 그렇고 newline 설정을 추가해주시는게 좋을 것 같네요

혼자 진행할 땐 크게 상관없지만, 협업 시 불필요한 file change가 생길 수 있습니다.

![image](https://user-images.githubusercontent.com/34656258/74032003-406eb100-49f6-11ea-875f-be6d0f72f939.png)

https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

> 인텔리제이에서 자동으로 저장 시 newline을 붙이도록 하는 설정

![image](https://user-images.githubusercontent.com/34656258/69198460-1be20600-0b78-11ea-83cd-c8fc5189c7ba.png)

2020-04-07 12:21 UTC, kyucumber commented on BE-workspace/src/main/java/com/codesquad/signup4/controller/auth/UserLoginController.java
> +  public ResponseEntity<Result> login(@RequestBody Map<String, String> userData, HttpSession httpSession) {
굳이 `Map<String, String>` 형태로 파라미터를 구성하신 이유가 있을까요?
한번 더 꺼내야 하는 번거로움이 있을 것 같은데.. 아래에 보니 Dto 형태로 사용하신 게 있던데
`@RequestBody`로 받는 `Map`을 dto 형태의 객체로 변경하신 뒤 추가로 `@Valid`와 같은 어노테이션을 이용하시면

```
if (!LoginDataVerifyUtil.checkUserIDformat(userID)) {
```

위와 같은 중복적으로 체크하는 부분도 제거할 수 있을 것 같네요

### Spring Boot `@Valid` annotation

- https://www.baeldung.com/spring-boot-bean-validation#implementing-a-rest-controller
- https://wedul.site/448

2020-04-07 12:21 UTC, tramyu commented on BE-workspace/src/main/java/com/codesquad/signup4/controller/auth/UserLoginController.java
> +    User user = userRepository.findByUserID(userID); //TODO orElseThrow가 왜 안먹지?
요건 인터페이스 반환 타입이 User라 orElseThrow를 사용할 수 없겠네요

기존 JPA 사용 시 Repository 기본 반환 값들이 Optional<User>로 되어있었을 거에요

JDBC라 Optional로 변경해도 잘 동작하는지는 잘 모르겠네요, 한번 체크해보세요

2020-04-07 12:21 UTC, tramyu commented on BE-workspace/src/main/java/com/codesquad/signup4/controller/userapi/APIUserDetailController.java
> +            user.getUserID(), user.getPassword(), user.getEmail(), user.getGender(),
user에 많이 접근하고 있는데 user를 아예 넘겨버릴수도 있을 것 같아요

2020-04-07 12:21 UTC, tramyu commented on BE-workspace/src/test/java/com/codesquad/signup4/UserDetailControllerTest.java
> +@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
이런 컨트롤러 테스트는 `@WebMvcTest`를 사용하고 Repository와 같은 부분들은 `@MockBean` 등으로 Mocking 해서 처리하실 수 있습니다.

`@SpringBootTest`는 굉장히 오래 걸려요.. 보통 빌드 시 테스트도 같이 돌리기 때문에 이 테스트가 늘어나면 늘어날수록 빌드 시간도 길어집니다.

https://meetup.toast.com/posts/124

관련해서 아직 접해보지 못하셨다면 그냥 넘어가신 뒤 나중에 찾아보셔도 괜찮습니다.
혹시나 관심이 있으시다면 Mockito, WebMvcTest, MockBean 등의 키워드로 찾아보세요

2020-04-07 12:21 UTC, tramyu commented on BE-workspace/src/test/java/com/codesquad/signup4/UserDetailControllerTest.java
> +    assertThat(responseEntity.getBody()).isNotNull();
행위와, 결과에 대한 체크 등등이 분리되어 있지 않아서 코드를 모르는 사람이 보면 좀 보기 힘들 수 있는데요, 만약 가독성이 좋지 않다고 느껴지신다면 아래 남긴 내용에 대해 한번 살펴보세요

많은 분들이 Given when then 패턴이라고 부르면서 나누는 패턴이 있는데요, 한번 관심있으시면 살펴보세요

https://blog.codecentric.de/en/2017/09/given-when-then-in-junit-tests/

2020-04-07 12:21 UTC, tramyu commented on BE-workspace/src/test/java/com/codesquad/signup4/LoginDataVerifyUtilTest.java
> +@SpringBootTest
이런 단순한 Util 테스트는 `@SpringBootTest` 없이 만드는게 좋을 것 같아요.

`@SpringBootTest`를 붙이고 테스트 해보신 뒤, `@SpringBootTest`를 제거하고 돌려보세요

여기 테스트에서는 스프링 컨텍스트가 올라올 필요가 없어서 제거하셔도 잘 동작할 것 같아요

2020-04-07 12:21 UTC, tramyu commented on BE-workspace/src/main/resources/schema.sql
> +    user_iD varchar(64),
```suggestion
    user_id varchar(64) UNIQUE,
```

아까 위 코드를 잠시 보니 user_id, email, mobile은 unique여야 할 것 같아요

2020-04-07 12:21 UTC, tramyu commented on BE-workspace/src/main/resources/application.properties
> +logging.file.name=${logging.file.path}/dev_log.log
혹시 로깅 등의 설정에 관심이 있으시다면 logback에 대해 한번 살펴보세요

https://www.baeldung.com/spring-boot-logging#logback-configuration-logging

위의 4. Logback Configuration Logging 항목을 보시면 됩니다.

2020-04-07 12:21 UTC, tramyu commented on BE-workspace/src/main/java/com/codesquad/signup4/dto/UserCreateDto.java
> +    private String userID;
아래에 isValid를 만드셨는데 api 요청에 받을 dto라면 아래처럼 체크할수도 있어요

위에 관련 문서를 남겨두었습니다. (`@Valid`)

```suggestion
    @NotBlank(message = "userId는 공백일 수 없습니다")
    private String userID;
```

2020-04-07 12:21 UTC, tramyu commented on BE-workspace/src/main/java/com/codesquad/signup4/dto/Result.java
> +    private boolean valid;
제가 요구사항을 명확히 몰라서 그런 것 같은데
`valid`라는 걸 봤을 때 어떤 목적으로 둔건지 잘 이해가 가지 않네요

보통 status code, timestamp, message 등을 두는데 valid라는걸 두는 경우는 처음이라서 어떤 용도인지 궁금하네요

2020-04-07 12:34 UTC, tramyu commented on BE-workspace/src/main/java/com/codesquad/signup4/controller/utils/LoginDataVerifyUtil.java
> +    String checkFormat = "(?i)^(?=.*[a-z])[a-z0-9]{8,20}$";
이런것도 javax validation 패키지의 어노테이션등을 활용에 dto에서 바로 해줄수 있어요

```java
@Pattern(
    regexp = "^4[0-9]{12}(?:[0-9]{3})?$", 
    message = "Only Visa cards are accepted."
    ) 
private String cardNumber;
```

2020-04-10 07:55 UTC, honux77 commented on BE-workspace/build.gradle
> +	compile group: 'io.springfox', name: 'springfox-swagger-ui', version: '2.7.0'
오오 감사합니다. 트램 아직 gradle 공부를 안 해서.. 슬슬 gradle도 해야겠네요.

2020-04-10 07:56 UTC, honux77 commented on BE-workspace/src/main/java/com/codesquad/signup4/controller/auth/UserLoginController.java
> +    User user = userRepository.findByUserID(userID); //TODO orElseThrow가 왜 안먹지?
Optional로 가능해요. 권장

2020-04-10 07:58 UTC, merged